config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'student#home'
  get 'about' , to: 'student#about'
  resources :articles
  get 'signup' , to: 'users#new'
  resources :users, except: [:new]
  get 'login' , to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end 

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum:25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum:105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?


  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:alert] = "You must login to continue."
      redirect_to login_path
    end
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]

  def show
    @article = Article.find(params[:id])
  end
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @article = Article.new

  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article saved successfully."
      redirect_to @article
    else
      render 'new'
    end
  end 

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end 

  private

  def require_same_user
    if current_user != @article.user.
      flash[:alert] = "You can edit and delete your own article."
      redirect_to @article
    end
  end

  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  def create
    @category = Category.new (category_params)
    if @category.save
      flash[:notice] = "Category created successfully."
      redirect_to @category
    else
      render 'new' 
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end 

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated successfully."
      redirect_to @category
    else
      render 'edit'
    end
  end
  
 
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user

    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path

  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)  
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information has been successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "Welcome to the Jini Blog #{@user.username}. You are signup successful!"
      redirect_to articles_path
    else
      render 'new'
    end
  end 

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])     
  end
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account."
      redirect_to @user
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravata_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravata_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravata_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= render'shared/errors', obj: @article %>
  <div>
    <%= form_with(model: @article, local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label " %>
        <div class="col-8">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.label :description, class: "col-2 col-form-label " %>
        <div class="col-8">
          <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.label :category, class: "col-2 col-form-label " %>
        <div class="col-8">
          <%= f.collection_select(:category_ids, Category.all, :id, :name, 
                  { prompt: "Make your selection from the list below (can be empty)"}, 
                  {multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
        </div>
      </div>
      <div class="form-group row justify-content-center" > 
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="text-center mt-2">Edit Article</h1>
  <%= render 'form' %>
  <p>
    <%= link_to 'Cancel and Return to Listing Articles', articles_path %>
  </p>
</div>

app/views/articles/index.html.erb
<div id="page-content">
  <div class="container-fluid">
    <h1 class="text-center mt-3">Listing all Articles</h1>
    <div class="table-responsive shadow p-3 mb-5 bg-white rounded">
      <table class="table">
        <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Author</th>
          <th colspan = 3 >Action</th>
        </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= article.user.username if article.user %></td>

            <td><%= link_to 'Show',article_path(article) %></td>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <td><%= link_to 'Edit',edit_article_path(article) %></td>
              <td><%= link_to 'delete', article_path(article), method: :delete, data: { confirm: "Are you sure?"} %></td>
            <% end %>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  <p>
    <%= link_to 'New Article', new_article_path %>
  </p> 
  <div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="text-center mt-2">Create New Article</h1>
  <%= render 'form' %>
  <p>
    <%= link_to 'Return to Listing Articles', articles_path, class: "col-1" %>
  </p>
</div>

app/views/articles/show.html.erb
<%# <p id="notice"><%= notice %></p> 
<div class="container">

  <p><strong>Title:</strong><%= @article.title %></p>
  <p>
    <strong>Description:</strong>
    <%= @article.description %>
  </p>
    <p>
    <strong>Author:</strong>
    <%= @article.user.username if @article.user %>
  </p>
  <p>
    <%= link_to 'Return to Listing Articles', articles_path %>
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <%= link_to 'delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
  </p>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-2">Update Category</h1>
<div class="container">
  <%= render'shared/errors', obj: @category %>
  <div>
    <%= form_with(model: @category, local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :name, "Category Name", class: "col-2 col-form-label"%>
        <div class="col-8">
          <%= f.text_field :name, class: "form-control"%>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.submit class: "btn btn-primary"%>
      </div>
    <% end %> 
  </div>  
  <div class="mb-3">
    <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
  </div>
</div>
  
  

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-title"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-2">Create Category</h1>
<div class="container">
  <%= render'shared/errors', obj: @category %>
  <div>
    <%= form_with(model: @category, local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :name, "Category Name", class: "col-2 col-form-label"%>
        <div class="col-8">
          <%= f.text_field :name, class: "form-control"%>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.submit class: "btn btn-primary"%>
      </div>
    <% end %> 
  </div>  
  <div class="mb-3">
    <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
  </div>
</div>
  
  

app/views/categories/show.html.erb
<h1 class="text-center mt-2">Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <h5 class="card-category"><%= render article.categories %></h5>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <h5 class="card-description"><%= link_to article.description, article_path(article), class: "text-success" %></h5>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_message.html.erb
<div class="container-fluid">
  <% flash.each do |name, msg|%>
    <div class="alert alert-<% name == "notice"? "success" : "danger" %> alert-dismissible fade show" role="alert">
      
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# <a class="navbar-brand" id="logo" href="#">Jini Blog</a> %>
  <%= link_to "Jini Blog", root_path, class:"navbar-brand", id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Blogers", users_path, class:"nav-link" %>     
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path(current_user), class: "dropdown-item" %>
          <% end %>
          <%= link_to "View article", articles_path, class: "dropdown-item" %>         
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile[<%= current_user.username %>]
          </a>
          <div class="dropdown-menu">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>  
            <%= link_to "Change your profile", edit_user_path(current_user), class: "dropdown-item" %>          
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"}  %>         
          </div>
        </li>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class:"nav-link" %>     
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, method: :delete, class:"nav-link" %>     
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class:"nav-link" %>     
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class:"nav-link"%>     
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading" >The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    <% end %>
  </ul>
</div>
<% end %>

app/views/student/about.html.erb
<h1>This is about page</h1>

<p>
  <%= link_to 'Listing Articles', articles_path %>
  <%= link_to 'Home page', root_path %>
</p>

app/views/student/home.html.erb
<div id="page-content">
  <div class="container-fluid" id="home-content">
    <div class="jumbotron text-center text-black">
      <h1 class="display-4">Jini Blog!</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%# <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a> %>
      <%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg"%>
    </div>
  </div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/users/_form.html.erb
<div class="container">
  <%= render'shared/errors', obj: @user %>
  <div>
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :username, class: "col-2 col-form-label"%>
        <div class="col-8">
          <%= f.text_field :username, class: "form-control"%>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.label :email, class: "col-2 col-form-label"%>
        <div class="col-8">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.label :password, class: "col-2 col-form-label"%>
        <div class="col-8">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row"> 
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update Profile", class: "btn btn-primary")%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1 class="text-center mt-2">Your profile</h1>
  <%= render 'form' %>
  <p>
    <%= link_to 'Return to Listing Articles', articles_path, class: "col-1" %>
  </p>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Jini Bloggers</h1>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravata_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-info text-danger", method: :delete,
                    data: { confirm: "Are you sure that you want to delete the user account and all associated articles?" } %>
              <% end %>
            <% end %>

          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-center mt-2">Sign Up for Jini Blog</h1>
  <%= render 'form' %>
  <p>
    <%= link_to 'Return to Listing Articles', articles_path, class: "col-1" %>
  </p>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="text-center mt-2"> <%= @user.username %>  profile</h1>
  <%= gravata_for @user, size: 200 %>
  <% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
  <% end %>
</div>